### ISSUE TITLE
how does the versioning work?

### ISSUE THREAD

**Issue by mi32dogs** [arambalakjian/DataObject-as-Page#61]
Hi, thank you for this great module, I have one question.

I have enable versioning, but I do not get a history tab on my DataObject, how does the versioning work?

**Comment by dhensby** [comment]
Currently there is no History feature. The versioning is intended just to allow staging and publishing of the DataObjects and not roll-backs (though it would be possible if the feature was implemented).

However, 3.x handles pages in gridfields and ModelAdmin far more smoothly than 2.x and therefore I'd recommend using https://github.com/silverstripe/silverstripe-lumberjack as a better way to manage pages, rather than creating Page-like DataObjects.
